### ISSUE TITLE
[FIREFOX] XPI need to be signed

### ISSUE THREAD

**Issue by benyaminl** [Smankusors/iSTTSHelper#4]
Hello thon, I come back with some problem, since FF ga bolehin addons tanpa signing cert, terus gimana cara pasangnya ke FFNya? any ideas?

**Comment by Smankusors** [comment]
kan... dah aku sign... XPI nya?
https://github.com/Smankusors/iSTTSHelper/releases

**Comment by benyaminl** [comment]
@Smankusors Maaf ternyata yang dari AMO yang aku coba... thanks thanks
